service: coilab-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 29
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${env:BUCKET_DESIGN}/*
            - arn:aws:s3:::${env:BUCKET_PROJECTS_DOCUMENTS}/*
  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}
    COGNITO_REGION: ${env:COGNITO_REGION}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    CORS_ORIGIN: ${env:CORS_ORIGIN, '*'}
    BUCKET_DESIGN: ${env:BUCKET_DESIGN}
    BUCKET_PROJECTS_DOCUMENTS: ${env:BUCKET_PROJECTS_DOCUMENTS}

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - '@aws-sdk/*'
    external:
      - '@nestjs/microservices'
      - '@nestjs/microservices/microservices-module'
      - '@nestjs/websockets/socket-module'
      - '@nestjs/platform-express'
      - '@fastify/view'
      - 'class-transformer/storage'

functions:
  api:
    handler: src/main.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{proxy+}
